os:
  - osx
  - linux

language: cpp
sudo: required

script:
  - git clone https://github.com/thomasgeissl/ofTravis.git
  - source ./ofTravis/common/export.sh
  - source ./ofTravis/${TRAVIS_OS_NAME}/install_oF.sh
  - if [ "$TRAVIS_OS_NAME" = linux ]; then sudo apt install libgit2-dev -y; fi
  - source ./ofTravis/common/compile_app.sh
  - if [ "$TRAVIS_OS_NAME" = osx ]; then ./scripts/fix_dylib.sh; fi
  - source ./ofTravis/common/package_app.sh

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then source ./ofTravis/osx/add_certificate.sh; fi

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: ${HOME}/packaged/*
  draft: true
  skip_cleanup: true
  on:
    tags: true
