os:
  - linux
  - osx

language: cpp
sudo: required

script:
  - git clone https://github.com/thomasgeissl/ofTravis.git
  - source ./ofTravis/common/export.sh
  - source ./ofTravis/${TRAVIS_OS_NAME}/install_oF.sh
  - if [ "$TRAVIS_OS_NAME" = osx ]; then sudo apt install libgit-dev -y; fi
  - source ./ofTravis/common/compile_app.sh
  # TODO: on osx fix rpath
  - source ./ofTravis/common/package_app.sh
#   - source ./ofTravis/common/compile_addon_examples.sh
#   - source ./ofTravis/common/package_addon.sh

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then source ./ofTravis/osx/add_certificate.sh; fi

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: ${HOME}/packaged/*
  draft: true
  skip_cleanup: true
  on:
    tags: true
