name: build-linux64-and-arm

on: [push, pull_request]
    
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: install
    - uses: actions/checkout@v2
      run: ./scripts/linux/install.sh

